version: '3.4'

services:
  rockpaperscissor:
    image: rockpaperscissor
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
